# linux matrix
language: python
os: linux
python:
    - "3.6"
    - "3.5"
    - "2.7"
env:
    - CONDA= EXTRAS= 
    - CONDA=1 EXTRAS=
    - CONDA= EXTRAS=1
    - CONDA=1 EXTRAS=1

matrix:
    include:
        # Linux 3.7
        - os: linux
          dist: xenial
          language: python
          python: 3.7
        # Linux 3.7 conda
        - os: linux
          dist: xenial
          language: python
          python: 3.7
          env: CONDA=1 
        # Linux 2.7 montepython_master
        - os: linux
          dist: xenial
          language: python
          python: 2.7
          env: MONTEPYTHONMASTER=1 
        # Linux 2.7 montepython_3.1.0
        - os: linux
          dist: xenial
          language: python
          python: 2.7
          env: MONTEPYTHON310=1 
        # Linux 2.7 montepython_master conda
        - os: linux
          dist: xenial
          language: python
          python: 2.7
          env: MONTEPYTHONMASTER=1 CONDA=1 
        # Linux 2.7 montepython_3.1.0 conda
        - os: linux
          dist: xenial
          language: python
          python: 2.7
          env: MONTEPYTHON310=1 CONDA=1 
        # OSX
        - os: osx
          language: generic
        # OSX conda
        - os: osx
          language: generic
          env: CONDA=1 

before_install:
    # OSX setup
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
          python3 -m venv environment;
          source environment/bin/activate;
      fi

install:
    - if [[ "$CONDA" == 1 ]];
      then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p $HOME/miniconda;
          export PATH="$HOME/miniconda/bin:$PATH";
          hash -r;
          conda config --set always_yes yes --set changeps1 no;
          conda update -q conda;
          conda info -a;
          conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION;
          source activate test-env;
      fi;
    - if [[ "$MONTEPYTHON310" == 1 ]];
      then
          wget https://github.com/brinckmann/montepython_public/archive/3.1.0.tar.gz;
          tar -xf 3.1.0.tar.gz;
          pip install argparse;
          pip install montepython_public-3.1.0/ --no-deps;
      fi;
    - if [[ "$MONTEPYTHONMASTER" == 1 ]];
      then
          wget https://github.com/brinckmann/montepython_public/tarball/master;
          tar -xf master;
          pip install argparse;
          pip install brinckmann-montepython_public-*/ --no-deps;
      fi;
    - pip install Cython numpy;
    - if [[ "$EXTRAS" == 1 ]];
      then
          pip install -r requirements.txt;
      else
          pip install -r requirements_minimal.txt;
      fi
    - pip install pytest-cov codecov;
    - pip install flake8 pydocstyle sphinx sphinx_rtd_theme;

before_script:
    # Test for pep-compliance
    - flake8 anesthetic tests

    # Test for documentation style
    - pydocstyle --convention=numpy anesthetic

# Run tests
script:
      python -m pytest tests --cov=anesthetic;

# Run coverage summary
after_success:
    - codecov
