#!/bin/bash

echo "Running PEP code style tests"
flake8 anesthetic anesthetic/gui tests

echo "Running docstring checks"
pydocstyle --convention=numpy anesthetic

echo "Running code tests"
CPU_COUNT=$(python -c 'import multiprocessing; print(multiprocessing.cpu_count())')
python -m pytest -n $CPU_COUNT
