#!/bin/bash

echo "Running PEP code style tests"
flake8 anesthetic anesthetic/gui tests

echo "Running docstring checks"
pydocstyle --convention=numpy anesthetic

echo "Running code tests"
python -m pytest -n auto
