#!/usr/bin/env python3
import argparse
import matplotlib.pyplot as plt
from rhinestone.plot import RunPlotter

# Parse arguments
description = "Nested sampling visualisation"
parser = argparse.ArgumentParser(description=description)
parser.add_argument('file_root', type=str, help="File name root of nested sampling run")
args = parser.parse_args()

# Generate the rhinestone plotter
plotter = RunPlotter(args.file_root)
plt.show()
