name: PR checks

on:
  pull_request:
    branches: [master]

jobs:
  version-is-unit-incremented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Upgrade pip and install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install packaging
      - name: Check version number
        run: python ./bin/check_version.py
